parameters:
    database_host: 37.187.245.156
    database_port: 3306
    database_name: AppMusicRecommender
    database_user: giodres
    database_password: giodres
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: s0p0rt3
    database_driver: pdo_mysql
    database_path: null
