# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    imp_service_library : ImpServiceLibrary\UserServiceLibrary
    imp_builder_repository : Infrastructure\UserBuilderRepository

services:

  entity.manager:
    class:     Infrastructure\UserBuilderRepository
    arguments: [ @doctrine.orm.entity_manager ]

  imp.service.library:
      class:     ImpServiceLibrary\UserServiceLibrary
      arguments : [  @service_container , @impl.builder.repository ]

  impl.builder.repository:
        class:     Infrastructure\UserBuilderRepository
        arguments : [  @doctrine.orm.entity_manager  ]

  imp.service.registration:
        class:     AppBundle\Controller\RegistrationController
        arguments: [@imp.service.library]



  search.controller:
          class:     AppBundle\Controller\SearhController
          arguments: [@imp.service.library]

  music.imp.service.library:
        class:     ImpServiceLibrary\MusicServiceLibrary
        arguments : [  @service_container , @impl.builder.repository ]